#   Foundation Configuration
#     Version: 1.2
#     Author: Robert Williams
#  --------------------------
#  Errors on configuration load can be due to many factors:
#    1. Tabs (YAML files are very particular and require spaces, not tabs.)
#    2. Indents (YAML files are also particular in that the indentation is very
#                important, therefore you must ensure that the indentation is
#                similar to the default config.yml.)
#    3. Apostrophes (Strings, or the text between the quotation marks and
#                    apostrophes are very sensitive. Typing "don't" can force
#                    an "escape," which can alter how the plugin reads this file.)

# MongoDB Connection Settings
#   uri: Your URI connection string provided by MongoDB. Begins with 'mongodb://'
#   database: Your database for storing collections.
#   player_data_collection: Your collection for player data.
mongodb:
  uri: ""
  database: ""
  player_data_collection: ""


# Server Variables
#   Change at your own risk.
server:
  spawn: ""

# Player Join Settings
#   join_message_enable: Set to 'true' or 'false' to enable or disable join messages.
#   join_message_format: Set to "playername" or "displayname" to choose the join message
#                          format. If the player does not have a display name (or nickname)
#                          then the "playername" format will be used. DO NOT USE
#                          firstjoin FORMAT.
#   playername: Set the playername format. Valid placeholders are:'#player#'
#   displayname: Set the displayname format. Valid placeholders are: '#player#' and
                                  #                  '#displayname#'
#   firstjoin: Set the first join format for when a user first joins the server. Valid
#              placeholders are: '#total#'
playerjoin:
  join_message_enable: true
  join_message_type: "playername"
  join_sounds_enable: true
  message_format:
    playername: "&8[&a+&8] &a#player#"
    displayname: "&8[&a+&8] &a#displayname# &8(&a#player#&8)"
    firstjoin: "&8[&a+&8] &a#player# &8(&f##total#&8)"

# Player Leave Settings
#   leave_message_enable: Set to 'true' or 'false' to enable or disable leave messages.
#   leave_message_format: Set to "playername" or "displayname" to choose the leave message
#                          format. If the player does not have a display name (or nickname)
#                          then the "playername" format will be used.
#   playername: Set the playername format. Valid placeholders are:'#player#'
#   displayname: Set the displayname format. Valid placeholders are: '#player#' and
#                  '#displayname#'
playerleave:
  leave_message_enable: true
  leave_message_type: "playername"
  leave_sounds_enable: true
  message_format:
    playername: "&8[&c-&8] &c#player#"
    displayname: "&8[&c-&8] &c#displayname# &8(&c#player#&8)"

# Economy Settings
#   starting_balance: The balance that a user starts at when initially joining the server.
economy:
  starting_balance: 0

# Gamemode Settings
#   use_lowercase_names: For gamemode placeholder in gamemode messages. Normal names are
#                        like 'Survival' and lowercase names are like 'survival.'
gamemode:
  use_lowercase_names: false

identity:
  date_format: "full"

# Message Settings
#   Edit to your preferences to match the rest of your server.
messages:
  error:
    no_perms: "&7You do not have permission to do that!"
    player_offline: "&7The player &c#player#&7 is not online."
    player_missing: "&7The player &c#player#&7 does not exist."
  command:
    feed:
      usage: "&eUsage: &7/feed &f[player]"
      console_error: "&cThe console may not be fed!"
      feeder_message: "&7You have fed &f#feedee#&7."
      feedee_message: "&7You have been fed by &f#feeder#&7."
      feeded_message: "&7You have been fed!"
    gamemode:
      usage: "&eUsage: &7/gamemode &f[player] <gamemode>"
      console_error: "&cThe console's gamemode may not be changed!"
      invalid_gamemode: "&7The gamemode &c#gamemode# &7does not exist!"
      gamemoder_message: "&7You have changed &f#gamemodee#&7's gamemode to: \n&f#gamemode#"
      gamemodee_message: "&7Your gamemode has been changed by &f#gamemoder#&7 and is now: \n&f#gamemode#"
      gamemoded_message: "&7Your gamemode has been changed to: &f#gamemode#"
    heal:
      usage: "&eUsage: &7/heal &f[player]"
      console_error: "&cThe console may not be healed!"
      healer_message: "&7You have healed &f#healee#&7."
      healee_message: "&7You have been healed by &f#healer#&7."
      healed_message: "&7You have been healed!"
    identity:
      usage: "&eUsage &7/identity &f[player]"
      console_error: "&cThe console may not be identified!"
      color:
        online: "&a"
        offline: "&c"
      regular_format:
        - "&8--------------------"
        - "      &7&lPlayer Identity"
        - "&8--------------------"
        - "&7Player: &e#player# &7(#status#&7)"
        - "&7Displayname: &e#displayname#"
        - "&7Last Login: &e#last_date#"
        - "  &f#time_since#"
      privileged_format:
        - "&8-----------------------------------"
        - "      &7&lPlayer Identity &8&l- &c&lPrivileged View"
        - "&8-----------------------------------"
        - "&7Player: &e#player# &7(#status#&7)"
        - "&7Displayname: &e#displayname#"
        - "&7IP Address: &e#ip#"
        - "&7First Login: &e#first_date#"
        - "&7Last Login: &e#last_date#"
        - "&7Time Since Last Login: &e#time_since_last_login# ago."
    nickname:
      usage: "&eUsage: &7/nickname &f[player] <nickname>"
      console_error: "&cThe console may not be nicknamed."
      nicknamer_message: "&7You have changed &f#nicknamee#&7's nickname to: \n&f#nickname#"
      nicknamee_message: "&7Your nickname has been changed by &f#nicknamer#&7 and is now: \n&f#nickname#"
      nicknamed_message: "&7Your nickname has been changed to: &f#nickname#"
    spawn:
      usage: "&eUsage: &7/spawn &f[set]"
      console_error: "&cThe console may not use spawn-related commands."
      spawn_teleport_message: "&7You have been teleported to spawn."
      spawn_set_message: "&7The spawn has been set to: &e#location#"
    uptime:
      format: "&7The server has been up for: &e#uptime#"
    ping:
      usage: "&eUsage: &7/ping &f[player]"
      console_error: "&cThe console may not be pinged!"
      pinger_message: "&f#pingee#&7's ping is: &f#ping#"
      pinged_message: "&7Your ping is: &f#ping#"
    vanish:
      usage: "&eUsage: &7/vanish &f[player]"
      console_error: "&cThe console may not be vanished!"
      vanisher_message: "&7You have set &f#vanishee#&7's vanish state to &f#state#&7."
      vanishee_message: "&7Your vanish state has been set to #state# by &f#vanisher#&7."
      vanished_message: "&7Your vanish state has been set to &f#state#&7."