#   Foundation Configuration
#     Version: 1.2
#     Author: Robert Williams
#  --------------------------
#  Errors on configuration load can be due to many factors:
#    1. Tabs (YAML files are very particular and require spaces, not tabs.)
#    2. Indents (YAML files are also particular in that the indentation is very
#                important, therefore you must ensure that the indentation is
#                similar to the default config.yml.)
#    3. Apostrophes (Strings, or the text between the quotation marks and
#                    apostrophes are very sensitive. Typing "don't" can force
#                    an "escape," which can alter how the plugin reads this file.)

# MongoDB Connection Settings
#   uri: Your URI connection string provided by MongoDB. Begins with 'mongodb://'
#   database: Your database for storing collections.
#   player_data_collection: Your collection for player data.
mongodb:
  uri: ""
  database: ""
  player_data_collection: ""

# Player Join Settings
#   join_message_enable: Set to 'true' or 'false' to enable or disable join messages.
#   join_message_format: Set to "playername" or "displayname" to choose the join message
#                          format. If the player does not have a display name (or nickname)
#                          then the "playername" format will be used. DO NOT USE
#                          firstjoin FORMAT.
#   playername: Set the playername format. Valid placeholders are:'#player#'
#   displayname: Set the displayname format. Valid placeholders are: '#player#' and
#                  '#displayname#'
#   firstjoin: Set the first join format for when a user first joins the server. Valid
#              placeholders are: '#total#'
playerjoin:
  join_message_enable: true
  join_message_format: "playername"
  message_format:
    playername: "&8[&a+&8] &a#player#"
    displayname: "&8[&a+&8] &a#displayname# &8(&a#player#&8)"
    firstjoin: "&8[&a+&8] &a#player# &8(&f##total#&8)"

# Player Leave Settings
#   leave_message_enable: Set to 'true' or 'false' to enable or disable leave messages.
#   leave_message_format: Set to "playername" or "displayname" to choose the leave message
#                          format. If the player does not have a display name (or nickname)
#                          then the "playername" format will be used.
#   playername: Set the playername format. Valid placeholders are:'#player#'
#   displayname: Set the displayname format. Valid placeholders are: '#player#' and
#                  '#displayname#'
playerleave:
  leave_message_enable: true
  leave_messageformat: "playername"
  message_format:
    playername: "&8[&c-&8] &c#player#"
    displayname: "&8[&c-&8] &c#displayname# &8(&c#player#&8)"

# Economy Settings
#   starting_balance: The balance that a user starts at when initially joining the server.
economy:
  starting_balance: 0

# Gamemode Settings
#   use_lowercase_names: For gamemode placeholder in gamemode messages. Normal names are
#                        like 'Survival' and lowercase names are like 'survival.'
gamemode:
  use_lowercase_names: false

messages:
  error:
    no_perms: "&7You do not have permission to do that!"
    player_offline: "&7The player &c#player#&7 is not online."
    player_missing: "&7The player &c#player#&7 does not exist."
  command:
    feed:
      usage: "&eUsage: &7/feed &f[player]"
      console_error: "&cThe console may not be fed!"
      feeder_message: "&7You have fed &f#feedee#&7."
      feedee_message: "&7You have been fed by &f#feeder#&7."
      feeded_message: "&7You have been fed!"
    gamemode:
      usage: "&eUsage: &7/gamemode &f[player] <gamemode>"
      console_error: "&cThe console's gamemode may not be changed."
      invalid_gamemode: "&7The gamemode &c#gamemode# &7does not exist!"
      gamemoder_message: "&7You have changed &f#gamemodee#&7's gamemode to: \n&f#gamemode#"
      gamemodee_message: "&7Your gamemode has been changed by &f#gamemoder#&7 and is now: \n&f#gamemode#"
      gamemoded_message: "&7Your gamemode has been changed to: &f#gamemode#"
    heal:
      usage: "&eUsage: &7/heal &f[player]"
      console_error: "&cThe console may not be healed!"
      healer_message: "&7You have healed &f#healee#&7."
      healee_message: "&7You have been healed by &f#healer#&7."
      healed_message: "&7You have been healed!"
    nickname:
      usage: "&eUsage: &7/nickname &f[player] <nickname>"
      console_error: "&cThe console may not be nicknamed."
      nicknamer_message: "&7You have changed &f#nicknamee#&7's nickname to: \n&f#nickname#"
      nicknamee_message: "&7Your nickname has been changed by &f#nicknamer#&7 and is now: \n&f#nickname#"
      nicknamed_message: "&7Your nickname has been changed to: &f#nickname#"